#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres
LEX = flex
YACC = bison
INC = 
CFLAGS = -std=gnu99
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/doctet

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/doctet

OBJ_DEBUG = $(OBJDIR_DEBUG)/Error.o $(OBJDIR_DEBUG)/ExtLib/extlib.def.o $(OBJDIR_DEBUG)/ExtLib/extlib.vect.o $(OBJDIR_DEBUG)/RenderDoc.o $(OBJDIR_DEBUG)/doctet.o $(OBJDIR_DEBUG)/lex.yy.o $(OBJDIR_DEBUG)/y.tab.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/Error.o $(OBJDIR_RELEASE)/ExtLib/extlib.def.o $(OBJDIR_RELEASE)/ExtLib/extlib.vect.o $(OBJDIR_RELEASE)/RenderDoc.o $(OBJDIR_RELEASE)/doctet.o $(OBJDIR_RELEASE)/lex.yy.o $(OBJDIR_RELEASE)/y.tab.o

LEX_FILES = lex.yy.c
YACC_FILES = y.tab.c y.tab.h y.output

all: debug #release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/ExtLib || mkdir -p $(OBJDIR_DEBUG)/ExtLib

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/Error.o: Error.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Error.c -o $(OBJDIR_DEBUG)/Error.o

$(OBJDIR_DEBUG)/ExtLib/extlib.def.o: ExtLib/extlib.def.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ExtLib/extlib.def.c -o $(OBJDIR_DEBUG)/ExtLib/extlib.def.o

$(OBJDIR_DEBUG)/ExtLib/extlib.vect.o: ExtLib/extlib.vect.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ExtLib/extlib.vect.c -o $(OBJDIR_DEBUG)/ExtLib/extlib.vect.o

$(OBJDIR_DEBUG)/RenderDoc.o: RenderDoc.c y.tab.h
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c RenderDoc.c -o $(OBJDIR_DEBUG)/RenderDoc.o

$(OBJDIR_DEBUG)/doctet.o: doctet.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c doctet.c -o $(OBJDIR_DEBUG)/doctet.o

$(OBJDIR_DEBUG)/lex.yy.o: lex.yy.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lex.yy.c -o $(OBJDIR_DEBUG)/lex.yy.o

$(OBJDIR_DEBUG)/y.tab.o: y.tab.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c y.tab.c -o $(OBJDIR_DEBUG)/y.tab.o

lex.yy.c: scan.l
	$(LEX) -o lex.yy.c scan.l

y.tab.c: parse.y
	$(YACC) -b y -d -v parse.y

y.tab.h: parse.y
	$(YACC) -b y -d -v parse.y
	

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/ExtLib
	rm -f $(LEX_FILES)
	rm -f $(YACC_FILES)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/ExtLib || mkdir -p $(OBJDIR_RELEASE)/ExtLib

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/Error.o: Error.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Error.c -o $(OBJDIR_RELEASE)/Error.o

$(OBJDIR_RELEASE)/ExtLib/extlib.def.o: ExtLib/extlib.def.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ExtLib/extlib.def.c -o $(OBJDIR_RELEASE)/ExtLib/extlib.def.o

$(OBJDIR_RELEASE)/ExtLib/extlib.vect.o: ExtLib/extlib.vect.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ExtLib/extlib.vect.c -o $(OBJDIR_RELEASE)/ExtLib/extlib.vect.o

$(OBJDIR_RELEASE)/RenderDoc.o: RenderDoc.c y.tab.h
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c RenderDoc.c -o $(OBJDIR_RELEASE)/RenderDoc.o

$(OBJDIR_RELEASE)/doctet.o: doctet.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c doctet.c -o $(OBJDIR_RELEASE)/doctet.o

$(OBJDIR_RELEASE)/lex.yy.o: lex.yy.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lex.yy.c -o $(OBJDIR_RELEASE)/lex.yy.o

$(OBJDIR_RELEASE)/y.tab.o: y.tab.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c y.tab.c -o $(OBJDIR_RELEASE)/y.tab.o



clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/ExtLib
	rm -f $(LEX_FILES)
	rm -f $(YACC_FILES)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

